# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-15 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0236_auto_20210831_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcvpermit',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
